### ISSUE TITLE
Exec seems to not force commands

### ISSUE THREAD

**Issue by MidMidd** [ShimmyMySherbet/ShimmysAdminTools#10]
When Exec is used, it does not seem to ignore permissions and throws a insufficient permission error to players.

**Comment by ShimmyMySherbet** [comment]
Are you using advanced permissions? As exec isn't currently compatible with it .

**Comment by MidMidd** [comment]
Nada, we're not using any sort of advanced permissions

**Comment by ShimmyMySherbet** [comment]
Could you send me a list of your plugins?

**Comment by MidMidd** [comment]
Sure thing, mind if I send it on discord?

**Comment by MidMidd** [comment]
Ah no matter, I'll just smack it here
![image](https://user-images.githubusercontent.com/41581549/120820088-e552bd00-c55c-11eb-9885-46095f2b86c4.png)

**Comment by ShimmyMySherbet** [comment]
Are you having this issue for all commands or just a specific few?

**Comment by MidMidd** [comment]
Only a specific few. From my test Exec and Mute just don't seem to do what they're supposed to

**Comment by ShimmyMySherbet** [comment]
You cannot Exec a player to run exec, and exec cannot run commands that check for permissions after the command's main body has finished execution.  Nothing can be done to fix exec for those commands.

**Comment by MidMidd** [comment]
Well, I would expect /give to work since it shouldn't check for permissions afterwards, but it still throws a permission error

**Comment by ShimmyMySherbet** [comment]
That's odd, /give should work normally, so I'll have a look

**Comment by MidMidd** [comment]
Could it be because we're using OpenMod instead of Rocket?

**Comment by ShimmyMySherbet** [comment]
oh, almost definitely, /exec won't work when using the openmod permissions system or for openmod commands

**Comment by MidMidd** [comment]
Ah, that'll do it

**Comment by MidMidd** [comment]
Well, glad that most of the commands work though

**Comment by MidMidd** [comment]
And I assume there's no real way to fix that either, correct?

**Comment by ShimmyMySherbet** [comment]
not without some serious bad practice patching, and this project is also meant to be dependency-less.

**Comment by MidMidd** [comment]
That's understandable, i'd say that most of the commands work so losing one doesn't matter too much. Well, thanks for the help!
