### ISSUE TITLE
Cannot open storage on vehicles.

### ISSUE THREAD

**Issue by ghost** [ShimmyMySherbet/ShimmysAdminTools#16]
Unable to open storage barricades mounted on vehicles with pointtool.

**Comment by ShimmyMySherbet** [comment]
I've looked into this, and I know the issue. Should be fixed in the next update.

**Comment by ShimmyMySherbet** [comment]
Sorry for the tremendous delay in fixing this, though this has since been fixed in the latest release.
Turned out barricades placed on vehicles used a different raymask than barricades placed on the ground.
