### ISSUE TITLE
How do i descend?

### ISSUE THREAD

**Issue by Ukraine1449** [ShimmyMySherbet/ShimmysAdminTools#2]
how do i desc?

**Comment by ShimmyMySherbet** [comment]
if you mean the /Descend command, that is part of the UEssentials plugin. You can use it as /Descend *distance*
You can get UEssentials here https://github.com/uEssentials/uEssentials/releases

**Comment by Ukraine1449** [comment]
I mean how to descend with /afly

**Comment by ShimmyMySherbet** [comment]
While Afly is enabled, look down, and press shift to descend.

**Comment by ShimmyMySherbet** [comment]
Due to the inactivity, I will assume that this answered your question. I might add an Afly Help command to the plugin for this.
