### ISSUE TITLE
Make a Command like /Storage <Player> 

### ISSUE THREAD

**Issue by dannythehacker** [ShimmyMySherbet/ShimmysAdminTools#31]
This Command would let you look in to the players inventory

**Comment by ShimmyMySherbet** [comment]
This command was already present in the plugin, though wholly unfinished and unstable.
If you want to check it out, have a look at /SeeInv <Player>. Though I don't recommend taking/adding items, as it can bug player states.
I don't have any current plans to fix the issues with the command. Currently it's useful to check the contents of a player's inventory, but that's about it.
