### ISSUE TITLE
New Utility

### ISSUE THREAD

**Issue by DFrostIce** [ShimmyMySherbet/ShimmysAdminTools#7]
Can you make it, so when you use the point with the Utility Tool, you get the SteamID and Player name of the owner from said structure?

**Comment by ShimmyMySherbet** [comment]
I'm planning to add a check owner command, so I might also make a point-tool for it as well.

**Comment by ShimmyMySherbet** [comment]
This has been added in the latest version, thanks for the suggestion.
https://github.com/ShimmyMySherbet/ShimmysAdminTools/releases/tag/v1.6
