### ISSUE TITLE
I have found a problem, in the last release, the build you made does not match the source

### ISSUE THREAD

**Issue by TH3AL3X** [ShimmyMySherbet/ShimmysAdminTools#8]

**Comment by ShimmyMySherbet** [comment]
I'm not sure what you're after here. Is the release outdated?

**Comment by TH3AL3X** [comment]
> I'm not sure what you're after here. Is the release outdated?

Nothing i got brain dead, for someone reasons the "DisableAbusableCommands" is not working when you do a rocket reload
